service: RuntimeBenchmark-Python-Noop
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  memorySize: "${env:LAMBDA_MEMORY, '128'}"
  region: ap-northeast-1
  timeout: 20

functions:
  noop:
    handler: handler.noop
