[package]
name = "hello"
version = "0.1.0"
edition = "2018"

[dependencies]
lambda_runtime = { version = "0.4.1" }
tokio = { version = "1.0", features = ["macros", "io-util", "sync", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "^1"
