service: RuntimeBenchmark-Rust-Noop

package:
  individually: true

provider:
  name: aws
  region: ap-northeast-1
  runtime: rust
  memorySize: "${env:LAMBDA_MEMORY, '128'}"
  versionFunctions: false
  lambdaHashingVersion: 20201221

plugins:
  - serverless-rust

custom:
  rust:
    dockerless: true

functions:
  noop:
    handler: hello
    events: []
