service: RuntimeBenchmark-TypeScript-Bench

plugins:
  - serverless-esbuild

custom:
  esbuild:
    # ⬇ダメだった…
    # tsconfig: tsconfig.json
    target: es2020
    minify: false
    watch:
      # anymatch-compatible definition (https://github.com/es128/anymatch)
      pattern: ['./src/*.ts']
      ignore: ['.serverless/**/*', '.build']

package:
  patterns:
    - '!node_modules/**'

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs14.x
  memorySize: "${env:LAMBDA_MEMORY, '128'}"
  versionFunctions: false
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - lambda:*
          Resource: "arn:aws:lambda:ap-northeast-1:*:function:*"

        - Effect: "Allow"
          Action:
            - logs:*
          Resource: "arn:aws:logs:ap-northeast-1:*:log-group:/aws/lambda/RuntimeBenchmark-*:*"

functions:
  benchmark:
    handler: src/index.benchmark
    events: []
    memorySize: 512
    timeout: 300
